// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ForgotMeNot",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "ForgotMeNot",
            targets: ["AppModule"],
            bundleIdentifier: "com.manur.ForgotMeNot",
            teamIdentifier: "W4GU8L4AQM",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "This app requires camera access for augmented reality experiences.")
            ],
            appCategory: .utilities
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]

        )
    ],
    swiftLanguageVersions: [.version("6")]
)
